export const allState = ["Andhra Pradesh",
    "Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Goa","Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttarakhand",
    "Uttar Pradesh",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli",
    "Daman and Diu",
    "Delhi",
    "Lakshadweep",
    "Puducherry"]

export const LifeInsuranceList = [
"Death Claim due to Accident rejected",
"Death claim (due to Accident) delayed",
"Death claim delayed",
"Death claim rejected",
"Free Look claim not received",
"Maturity claim not paid",
"Misseling & Fraud with Freelook",
"Misselling and Fraud sales",
"Moneyback not paid",
"Others",
"Policy Bond not received"
];

export const generalInsuranceList =[
"Commercial claim",
"Critical Illness",
"Death Claim due to Accident rejected",
"Death claim (due to Accident) delayed",
"Death claim delayed",
"Death claim rejected",
"Fidelity claim",
"Fire",
"Home Insurance",
"Misseling & Fraud",
"Motor Accident Insurance claim",
"Motor Claim",
"Motor Theft Claim",
"Others",
"Personal Accident",
"Property claim",
"Theft",
"Travel Insurance claim",
"Workmen Compensation"
]

export const healthInsuranceList = [
"Claim is delayed",
"Claim is rejected",
"Covid Claim Rejected",
"Covid Complaint Delay",
"Covid Complaint Shortsettled",
"Death Claim due to Accident rejected",
"Death claim (due to Accident) delayed",
"Death claim delayed",
"Death claim rejected",
"Deduction in claim",
"Group Insurance claim",
"Misseling & Fraud with Freelook",
"Misselling and Fraud sales",
"No response on the claim status",
"Others",
"Policy is cancelled",
"Policy not renewed"]

export const policyType =["Life Insurance", "General Insurance", "Health Insurance"]

export const partnerType =[
    "Hospital",				
"Hospital Employee",				
"Any Insurance Company Employee",				
"Any TPA Emplyee",				
"Insurance Company - Agents or Advisore",				
"Insurance Broker", 				
"Insurance Broker - Employee",				
"Corporate",				
"NBFC",				
"Any Financial Services Company",				
"Any Insurance Surveyor",				
"Any Motor Garages Employee",				
"Other's"				
]